### PR TITLE
Add active class when value is 0

### PR DESCRIPTION
**Pull request by nicolaslopezj**

### CODE REVIEW

**Comment by Chun-Yang** [comment]
@nicolaslopezj Thank you for your help.

Can you explain a little bit with some screen shot about the problem?

**Comment by 0o-de-lally** [comment]
I think this may be related to my issue: https://github.com/djhi/meteor-autoform-materialize/issues/86

**Comment by 0o-de-lally** [comment]
@Chun-Yang  Just confirmed that this fixes the issue locally, with no other issues. Please merge. Thanks in advance!

**Comment by Chun-Yang** [comment]
@keyscores @nicolaslopezj Thank you!

**Pull request merged**
