### PR TITLE
Added support for Materialize icons.

### PR DESCRIPTION
**Pull request by donwojtallo**
I hope it's ok.

### CODE REVIEW

**Comment by Chun-Yang** [comment]
Awesome! Can you add an example in the README.md?
You can add an additional type under https://github.com/djhi/meteor-autoform-materialize#additional-type

Thank you!

**Comment by donwojtallo** [comment]
This addition is actually not new input type. I made a new template for icon and updated `afFormGroup`. I'm not sure how to include this in README.md. I explain how it works below. Just tell me where to paste that.

You can add icon to any field like this:

```
{{> afQuickField name='subject' icon='person'}}
```

For blank space in place of icon:

```
{{> afQuickField name='subject' icon='none'}}
```

Just use "none" or any other word that is not recognized by MaterializeCSS.

For textarea:

```
{{> afQuickField name='message' type='textarea' icon='person'}}
```

To use icon only:

```
{{> afIcon_materialize icon='person'}}
```

**Comment by Chun-Yang** [comment]
You can treat it as a new input type and name it 'Input with icon'.
I will change the README after the merge.

**Comment by byennen** [comment]
:+1:

**Comment by donwojtallo** [comment]
What now? Will you merge it or you are waiting for me to do something?
I'm not very familiar with contributing yet, sorry.

**Comment by Chun-Yang** [comment]
I will merge it shortly. Give me some time.
Thank you!

**Comment by Chun-Yang** [comment]
Hey @djhi I merged it. Tell me your thought. We can publish a new version.

**Pull request merged**
